name: client.yaml

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'client/package.json'

      - name: Install dependencies
        run: yarn install

      - name: Build and Deploy
        run: yarn build && rsync -avz --delete dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/o0/client/