name: diploma.yaml

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore LaTeX Image Cache if it exists
        id: cache-docker-latex
        uses: actions/cache@v3
        with:
          path: ci/cache/docker/latex
          key: cache-docker-latex

      - name: Update LaTeX Image Cache if cache miss
        if: steps.cache-docker-latex.outputs.cache-hit != 'true'
        run: |
          docker pull 2109199812/docker-latex && mkdir -p ci/cache/docker/latex && docker image save 2109199812/docker-latex --output ./ci/cache/docker/latex/latex-image.tar

      - name: Use LaTeX Image Cache if cache hit
        if: steps.cache-docker-latex.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/docker/latex/latex-image.tar

      - name: Compile Diploma
        shell: bash
        run: |
          docker run --rm -i -v ./docs/:/diploma:Z 2109199812/docker-latex bash -c "make clean && make diploma.pdf"

      - name: Prepare release artifacts
        run: |
          mkdir -p gh-pages
          mv ./docs/diploma.pdf gh-pages/diploma.pdf

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: diploma
          path: gh-pages/
          retention-days: 1

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4