name: nginx.yaml

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/nginx.conf"
      - ".github/workflows/nginx.yaml"

jobs:
  nginx:
    name: Update Nginx Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Add known hosts
        run: ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Update and Test Nginx Config
        run: |
          scp .github/nginx.conf ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/nginx/sites-available/o0.network.temp.conf
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e;
            [ -f /etc/nginx/sites-available/o0.network.conf ] && sudo cp /etc/nginx/sites-available/o0.network.conf /etc/nginx/sites-available/o0.network.conf.bak || true;
            sudo mv /etc/nginx/sites-available/o0.network.temp.conf /etc/nginx/sites-available/o0.network.conf &&
            sudo nginx -t &&
            sudo systemctl reload nginx ||
            (sudo mv /etc/nginx/sites-available/o0.network.conf.bak /etc/nginx/sites-available/o0.network.conf 2>/dev/null || true; exit 1)
          "
