name: Website

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached app directory
        uses: actions/cache@v4
        with:
          path: app
          key: ${{ runner.os }}-app-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-app-

      - name: Build web app
        working-directory: app
        run: npm run build:web

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: app/dist/web
          branch: gh-pages
          target-folder: www